# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/configuration-reference/#jobs
jobs:
  build:
    docker:
      - image: ghcr.io/sushrut1101/docker:arch
    resource_class: large  
    steps:
      - checkout
      - run:
          name: "Build"
          command: 
            git config --global user.name "King" &&
            git config --global user.email "King@gmail.com" && 
            repo init -u https://github.com/LineageOS/android.git -b lineage-20.0 --git-lfs --depth=1 &&
            repo sync -j8 &&
            source .build/envsetup.sh &&
            lunch lineageos_whyred-userdebug &&
            brunch whyred &&
            cd out/target/product/whyred &&
            ls -al &&
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} out/target/product/whyred/d*.zip
      - store_artifacts:
           path: out/target/
            
          

